### ISSUE TITLE
Unexpected Version Comparison

### ISSUE THREAD

**Issue by cristinel24** [jelmer/debversion-rs#27]
### Description
I've encountered a scenario when using the `debversion` crate where comparing two versions results in a newer version being considered "Less" than an older one. This seems to be related to the behavior of the `explicit()` function, which trims leading zeros from the `upstream_version`. This might lead to inaccurate version comparisons.

### Code to Reproduce

```rust
use anyhow::{anyhow, Result};
use debversion::Version;

fn main() -> Result<()> {
    let version_one = "23.13.9-7";
    let version_two = "0.6.45-2";

    let version_diff = match (
        version_one.parse::<Version>(),
        version_two.parse::<Version>(),
    ) {
        (Ok(parsed_version), Ok(parsed_patch)) => Ok(parsed_version.cmp(&parsed_patch)),
        (Err(err), _) | (_, Err(err)) => Err(anyhow!(
            "{err}! version_one: {version_one:?}, version_two: {version_two:?}"
        )),
    }?;

    println!("Version diff: {version_diff:?}");
    Ok(())
}
```
```
Finished `dev` profile [unoptimized + debuginfo] target(s) in 5.65s
     Running `target\debug\debversion-test.exe`
Version diff: Less
```
### Expected Behavior
I expected the version `23.13.9-7` to be considered greater than `0.6.45-2`, similar to how the `python-debian` module handles this comparison.

### Potential Cause
It seems that the issue might stem from the `explicit()` function within the `Version` struct:

```rust
fn explicit(&self) -> (u32, String, String) {
    (
        self.epoch.unwrap_or(0),
        self.upstream_version.trim_start_matches('0').to_string(),
        self.debian_revision.as_deref().unwrap_or("0").to_string(),
    )
}
```

The function trims leading zeros from the `upstream_version`, which could be impacting the accuracy of version comparisons.

### Questions
1. **What is the reason behind trimming leading zeros from the `upstream_version` in the `explicit()` function?**
2. **Is this behavior intended for all version formats, or could it be problematic in specific cases like the one described above?**
3. **Is the crate intended to replicate the `python-debian` module's functionality and comparison logic?**

Thank you for your time.

**Comment by jelmer** [comment]
Thanks for the detailed bug report. This is indeed a bug.

FWIW the logic behind stripping the leading zeroes is so that

"000.1" is considered equivalent to "0.1"

this matches the behaviour in python-debian, e.g.:

```
>>> import debian.changelog
>>> debian.changelog.Version('0.1') == debian.changelog.Version('000.1')
True
```

**Comment by jelmer** [comment]
0.4.3 has been released with the fix
